name: Build and Deploy to Tomcat

on:
  push:
    branches:
      - master  # Trigger workflow on push to 'master' branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Pull the latest changes
      - name: Pull Latest Changes from Git
        run: |
          echo "Pulling latest changes from Git..."
          git fetch --all
          git reset --hard origin/master
        shell: cmd

      # Step 3: Verify Maven Path
      - name: Verify Maven Path
        run: |
          echo "MAVEN_HOME is set to: %MAVEN_HOME%"
          dir %MAVEN_HOME%\bin
        shell: cmd

      # Step 4: Build the Project with Maven
      - name: Build with Maven
        run: |
          set MAVEN_HOME=C:\apache-maven-3.9.9
          call "%MAVEN_HOME%\bin\mvn" clean package
        shell: cmd
