name: Build and Deploy to Tomcat

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Maven Environment Variables
      - name: Set Environment Variables
        run: |
          set M2_HOME=C:\apache-maven-3.9.9
          set PATH=%PATH%;%M2_HOME%\bin
          echo "M2_HOME is set to: %M2_HOME%"
          dir %M2_HOME%\bin
        shell: cmd

      # Step 3: Build the Project with Maven
      - name: Build with Maven
        run: |
          call "%M2_HOME%\bin\mvn" clean package
        shell: cmd
