name: CI Pipeline for Spring Boot App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Specify Java 11
        distribution: 'temurin'

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: List target directory (debugging)
      run: ls -l target/

    - name: Deploy to Tomcat Locally
      run: |
        # Ensure the WAR file exists
        if [ -f target/*.war ]; then
          echo "WAR file found, proceeding with deployment."
          WAR_FILE="target/*.war"
          DEPLOY_PATH="C:/Users/Mohtaram/Documents/Tomcat 9.0/webapps"

          # Copy WAR file to Tomcat webapps directory
          cp "$WAR_FILE" "$DEPLOY_PATH"

          # Restart Tomcat (local system)
          sudo systemctl restart tomcat
        else
          echo "WAR file not found! Deployment aborted."
          exit 1
        fi
