name: Build and Deploy to Tomcat

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Verify Access to C Drive
        uses: actions/checkout@v3
        
       # Step 2: Checkout the code
      - name: Verify Access to C Drive
        run: dir C:\
        shell: cmd
