name: Build and Deploy to Tomcat

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Maven Environment Variables
      - name: Debug Environment
        run: echo MAVEN_HOME=%MAVEN_HOME%
        shell: cmd

       # Step 2: Set Maven Environment Variables
      - name: Verify Maven Installation
        run: dir %MAVEN_HOME%\bin
        shell: cmd
