name: CI Pipeline for Spring Boot App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Source Code
    - name: Checkout Source Code
      uses: actions/checkout@v3

    # Step 2: Set Up JDK
    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Step 3: Cache Maven Dependencies
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build with Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Step 5: List Target Directory (Debugging)
    - name: List Target Directory
      run: ls -l target/

    # Step 6: Deploy to Tomcat
    - name: Deploy WAR to Local Tomcat
      run: |
        # Define variables
        WAR_FILE=$(find target/ -name "*.war")
        TOMCAT_USER=maaz
        TOMCAT_HOST=localhost
        TOMCAT_PATH="D:\Soft\webapps"

        # Deploy WAR file to Tomcat server
        scp -i ~/.ssh/id_rsa "$WAR_FILE" "$TOMCAT_USER@$TOMCAT_HOST:$TOMCAT_PATH"
 
