name: hello-world

on:
  push:
    branches:
      - master  # Trigger workflow on push to 'master' branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  my-job:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pull the latest code from your repository

      - name: Run Hello World
        run: echo "Hello World!"  # Run the 'Hello World' message
